# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.21.3
	yarn_mappings=1.21.3+build.2
	loader_version=0.16.9

# Forge Properties
	modid=make_bubbles_pop
	mc_version=1.21.3
	forge_version=53.0.25
	parch_mapping=2024.12.07
	mod_id = "make_bubbles_pop"
	mod_authors = "tschipcraft"

# Mod Properties
	mod_version = 0.3.1
	maven_group = net.tschipcraft
	archives_base_name = make_bubbles_pop

# Dependencies
	fabric_version=0.112.0+1.21.3
	midnightlib_version=1.6.4
