[versions]
stonecutter = "0.9.2"
stonecutter-postprocess = "2.1-beta.8"
mod-publish = "2.1.1"
loomx = "0.4.1"
neoforge-moddev = "2.0.141"
foojay = "1.0.0"
vanniktech-maven-publish = "0.35.0"
mixin = "0.8.5"
serialization-json = "1.7.3"
serialization-toml = "0.6.0"

[libraries]
kikugie-postprocess = { module = "dev.kikugie:postprocess", version.ref = "stonecutter-postprocess" }
mod-publish-plugin = { module = "me.modmuss50:mod-publish-plugin", version.ref = "mod-publish" }
kikugie-stonecutter = { module = "dev.kikugie:stonecutter", version.ref = "stonecutter" }
kikugie-loomx = { module = "dev.kikugie:loomx", version.ref = "loomx" }
foojay-resolver = { module = "org.gradle.toolchains:foojay-resolver", version.ref = "foojay" }
vanniktech-maven-publish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "vanniktech-maven-publish" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }
serialization-toml = { module = "dev.eav.tomlkt:tomlkt", version.ref = "serialization-toml" }

[plugins]
stonecutter = { id = "dev.kikugie.stonecutter", version.ref = "stonecutter" }
loom-back-compat = { id = "dev.kikugie.loom-back-compat", version.ref = "loomx" }
neoforged-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev" }
legacyforge-moddev = { id = "net.neoforged.moddev.legacyforge", version.ref = "neoforge-moddev" }
jsonlang-postprocess = { id = "dev.kikugie.postprocess.jsonlang", version.ref = "stonecutter-postprocess" }
mod-publish-plugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "mod-publish" }
