modLoader = "javafml"
loaderVersion = "[4,)"
license="Custom"
logoFile= "icon.png"
logoBlur=false

[[mods]]
modId = "make_bubbles_pop"
version = "${version}-neoforge"
displayName = "Make Bubbles Pop"
description='''
This client-side mod makes bubble particles pop and completely overhauls their behavior to make them rise realistically to the water surface.

It also adds bubble particles to opening chests, opening barrels and explosions underwater.
'''
authors="Tschipcraft"
displayURL="https://github.com/Tschipcraft/make_bubbles_pop/tree/archloom"
issueTrackerURL="https://github.com/Tschipcraft/make_bubbles_pop/issues"
updateJSONURL="https://api.modrinth.com/updates/gPCdW0Wr/forge_updates.json"
displayTest="IGNORE_ALL_VERSION"

[[dependencies.make_bubbles_pop]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.0.110-beta,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.make_bubbles_pop]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,1.21.1]"
    ordering = "NONE"
    side = "BOTH"

[[mixins]]
    config = "make_bubbles_pop.mixins.json"
