name: build
on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/archloom' }}
          add-job-summary: 'always' # maybe change to error only?
      - name: Make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Capture Fabric build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Make Bubbles Pop Fabric 1.20.6-1.21.1 (Unzip Me)"
          path: fabric/build/libs/make_bubbles_pop-*.jar
      - name: Capture Forge build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Make Bubbles Pop Forge 1.20.6-1.21.1 (Unzip Me)"
          path: forge/build/libs/make_bubbles_pop-*.jar
      - name: Capture NeoForge build artifact
        uses: actions/upload-artifact@v4
        with:
          name: "Make Bubbles Pop NeoForge 1.21-1.21.1 (Unzip Me)"
          path: neoforge/build/libs/make_bubbles_pop-*.jar
