name: build
on: [pull_request, push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          show-progress: false
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v5
      - name: Setup JDKs
        uses: actions/setup-java@v5
        with:
          # 17 for 1.18-1.20.4, 21 for 1.20.5-1.21.x, 25 for 26+.
          java-version: |
            17
            21
            25
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/dev' }}
          add-job-summary: 'always'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build all Stonecutter targets
        run: ./gradlew build
      - name: Collect jars
        run: ./gradlew buildAndCollect
      - name: Capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: "Make Bubbles Pop (Unzip Me)"
          path: build/libs/**/*.jar
      - name: Set job summary
        id: summary
        shell: bash
        run: |
          cat << EOF >> $GITHUB_STEP_SUMMARY
          <picture>
            <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/light-theme/success.svg">
            <img alt="✅ Success" src="https://raw.githubusercontent.com/Mqxx/GitHub-Markdown/main/blockquotes/badge/dark-theme/success.svg">
          </picture><br>

          **${{ github.event.repository.name }}** built successfully for all Stonecutter targets! [See changes since last release](https://github.com/${{ github.repository }}/blob/${{ github.sha }}/CHANGES.md).

          [Download artifacts via nightly.link](https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }})

          EOF
